### ISSUE TITLE
Grpc server stuck for certain tests

### ISSUE THREAD

**Issue by kaibocai** [microsoft/durabletask-go#58]
I encounter this issue when trying to set up durabletask-go as the testing image for durabletask-java integration tests. I can reproduce this issue in Java, Go, and JavaScript. 

Issue Description:
for a test suite contains two tests:
```go
func Test_Grpc_WaitForInstanceStart_Timeout(t *testing.T) {
	r := task.NewTaskRegistry()
	r.AddOrchestratorN("WaitForInstanceStartThrowsException", func(ctx *task.OrchestrationContext) (any, error) {
		// sleep 5 seconds
		time.Sleep(5 * time.Second)
		return 20, nil
	})

	cancelListener := startGrpcListener(t, r)
	defer cancelListener()

	id, err := grpcClient.ScheduleNewOrchestration(ctx, "WaitForInstanceStartThrowsException", api.WithInput("世界"))
	require.NoError(t, err)
	timeoutCtx, cancelTimeout := context.WithTimeout(ctx, time.Second)
	defer cancelTimeout()
	_, err = grpcClient.WaitForOrchestrationStart(timeoutCtx, id, api.WithFetchPayloads(true))
	if assert.Error(t, err) {
		assert.Contains(t, err.Error(), "context deadline exceeded")
	}
	time.Sleep(1 * time.Second)
}

func Test_Grpc_HelloOrchestration(t *testing.T) {
	r := task.NewTaskRegistry()
	r.AddOrchestratorN("SingleActivity", func(ctx *task.OrchestrationContext) (any, error) {
		var input string
		if err := ctx.GetInput(&input); err != nil {
			return nil, err
		}
		var output string
		err := ctx.CallActivity("SayHello", task.WithActivityInput(input)).Await(&output)
		return output, err
	})
	r.AddActivityN("SayHello", func(ctx task.ActivityContext) (any, error) {
		var name string
		if err := ctx.GetInput(&name); err != nil {
			return nil, err
		}
		return fmt.Sprintf("Hello, %s!", name), nil
	})

	cancelListener := startGrpcListener(t, r)
	defer cancelListener()

	id, err := grpcClient.ScheduleNewOrchestration(ctx, "SingleActivity", api.WithInput("世界"))
	require.NoError(t, err)
	timeoutCtx, cancelTimeout := context.WithTimeout(ctx, 30*time.Second)
	defer cancelTimeout()
	metadata, err := grpcClient.WaitForOrchestrationCompletion(timeoutCtx, id, api.WithFetchPayloads(true))
	require.NoError(t, err)
	assert.Equal(t, true, metadata.IsComplete())
	assert.Equal(t, `"Hello, 世界!"`, metadata.SerializedOutput)
	time.Sleep(1 * time.Second)
}
```
If running them in order the second test will timeout, although running them separately, both tests will succeed. It turns out that after running the first test, all other tests will timeout. The executor goroutine seems parking forever (not fetching work item and processing them. )

The step to reproduce the issue 
1. checkout branch `kaibocai/server-stuck-issue`
2. run `go test tests/grpc/grpc_test.go`

You will see the second test time-out. 
<img width="1254" alt="image" src="https://github.com/microsoft/durabletask-go/assets/89094811/ee459e1f-1172-4edb-947d-794d851c8f99">

I try to figure this out but without much luck. Appreciate it if you can help take a look @cgillum , @ItalyPaleAle , @shivamkm07

**Comment by ItalyPaleAle** [comment]
Feel free to ping me later and we can debug together. The first thing that comes to mind is that there may be a port conflict, maybe the test is trying to create a listener on an port that was already taken?

**Comment by shivamkm07** [comment]
Hey I debugged this today and was able to identify why it's getting stuck:

Here https://github.com/microsoft/durabletask-go/blob/28789e17ce0a2ccecc811ab02035e8c3df262a71/tests/grpc/grpc_test.go#L85 in the `Test_Grpc_WaitForInstanceStart_Timeout` test, in the orchestration you are sleeping for 5 seconds, but the whole test ends in ~2 seconds(1 second timeout for timeoutCtx and 1 second sleep in the end) and so after the test ends and grpc listener is cancelled(https://github.com/microsoft/durabletask-go/blob/28789e17ce0a2ccecc811ab02035e8c3df262a71/tests/grpc/grpc_test.go#L92), workflow is still running. Once grpc listener gets closed, corresponding work item stream is closed as well. Now when the orchestration completes and it is unable to send the signal to executor that the orchestration is completed(https://github.com/microsoft/durabletask-go/blob/28789e17ce0a2ccecc811ab02035e8c3df262a71/client/worker_grpc.go#L83) as the call errors out with log `failed to complete orchestration task: context canceled`. Since executor never receives the signal, it is still waiting for the orchestration to complete here: https://github.com/microsoft/durabletask-go/blob/28789e17ce0a2ccecc811ab02035e8c3df262a71/backend/executor.go#L129 and keeps waiting forever. That's why it keeps hanging and never receives any work item. 

It is actually already mentioned in the comment: https://github.com/microsoft/durabletask-go/blob/28789e17ce0a2ccecc811ab02035e8c3df262a71/backend/executor.go#L124
